#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Poker.AndroidClient.Resource", IsApplication=true)]

namespace Poker.AndroidClient
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public const int colorAccent = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int colorPrimary = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int colorPrimaryDark = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int lightText = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int logo = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070003
			public const int dashBoard_btnSend = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int dashBoard_etMessageText = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int dashBoard_lvMessages = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int dashBoard_textView = 2131165184;
			
			// aapt resource value: 0x7f070006
			public const int main_labelConnecting = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int main_logoImage = 2131165188;
			
			// aapt resource value: 0x7f070007
			public const int main_progressBar = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int main_relativeLayout = 2131165189;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DashBoard = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int dashboard_enterMessage = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int dashboard_send = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int dashboard_welcome = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int main_cannot_connect = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int main_connected = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int main_connecting = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int TextColorC3 = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
